#name: Terraform apply
#on: workflow_dispatch
#jobs:
##  Terraform_Init:
##    runs-on: self-hosted
##    steps:
##      - name: check out repo   code
##        uses: actions/checkout@v4
##      - name: Terraform init
##        run: |
##          terraform init -backend-config=env-dev/state.tfvars
##
##  Terraform_plan:
##    runs-on: self-hosted
##    steps:
##      - name: check out repo code
##        uses: actions/checkout@v4
##      - name: Terraform init
##        run: |
##          terraform plan -var-file=env-dev/main.tfvars
#
#  Terraform_Apply:
#    runs-on: self-hosted
#    steps:
#      - name: check out repo code
#        uses: actions/checkout@v4
#      - name: Terraform apply
#        run : |
##         because aws was not found in GitHub use account in some folders this like makes aws available in those folders mentioned
#          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#          terraform init -backend-config=env-dev/state.tfvars
#          terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
#
#        env :
#          vault_token : ${{ secrets.vault_token }}
#
#
##  Helm_Install_Applications:
##    needs: Terraform_Apply
##    runs-on: self-hosted
##    steps:
##      - name: check out repo code
##        uses: actions/checkout@v4
##        with:
##          repository: testVinaycicd/roboshop-helm
##          path: helm
##      - name: Helm charts
##        run : |
##          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
##          cd helm
##          make dev
##        env :
##          vault_token : ${{ secrets.vault_token }}

name: Terraform Apply
on: workflow_dispatch

jobs:
  terraform_init:
    runs-on: self-hosted
    steps:
      - name: Hello World
        run: echo "hello world"

  Terraform-Apply:
    runs-on: self-hosted
    needs: terraform_init  # ✅ Ensure this runs after `terraform_init `
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4
      - name: Terraform apply
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          terraform init -backend-config=env-dev/state.tfvars
          terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
        env:
          vault_token: ${{ secrets.vault_token }}

  Deploy-Cart:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-cart
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          aws eks update-kubeconfig  --name dev
          bash argocd.sh cart dev $GID

  Deploy-Catalogue:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-catalogue
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          aws eks update-kubeconfig  --name dev
          bash argocd.sh catalogue dev $GID

  Deploy-User:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-user
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          aws eks update-kubeconfig  --name dev
          bash argocd.sh user dev $GID

  Deploy-Shipping:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-shipping
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          aws eks update-kubeconfig  --name dev
          bash argocd.sh shipping dev $GID

  Deploy-Payment:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-payment
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          aws eks update-kubeconfig  --name dev
          bash argocd.sh payment dev $GID

  Deploy-Frontend:
    needs: Terraform-Apply
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-frontend
          path: app
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: testVinaycicd/roboshop-helm
          path: helm
      - name: Helm Install
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          cd app
          GID=$(git log --format="%H" -n 1)
          cd ../helm
          aws eks update-kubeconfig  --name dev
          bash argocd.sh frontend dev $GID