#name: Terraform apply
#on: workflow_dispatch
#jobs:
##  Terraform_Init:
##    runs-on: self-hosted
##    steps:
##      - name: check out repo code
##        uses: actions/checkout@v4
##      - name: Terraform init
##        run: |
##          terraform init -backend-config=env-dev/state.tfvars
##
##  Terraform_plan:
##    runs-on: self-hosted
##    steps:
##      - name: check out repo code
##        uses: actions/checkout@v4
##      - name: Terraform init
##        run: |
##          terraform plan -var-file=env-dev/main.tfvars
#
#  Terraform_Apply:
#    runs-on: self-hosted
#    steps:
#      - name: check out repo code
#        uses: actions/checkout@v4
#      - name: Terraform apply
#        run : |
##         because aws was not found in GitHub use account in some folders this like makes aws available in those folders mentioned
#          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
#          terraform init -backend-config=env-dev/state.tfvars
#          terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
#
#        env :
#          vault_token : ${{ secrets.vault_token }}
#
#
##  Helm_Install_Applications:
##    needs: Terraform_Apply
##    runs-on: self-hosted
##    steps:
##      - name: check out repo code
##        uses: actions/checkout@v4
##        with:
##          repository: testVinaycicd/roboshop-helm
##          path: helm
##      - name: Helm charts
##        run : |
##          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
##          cd helm
##          make dev
##        env :
##          vault_token : ${{ secrets.vault_token }}

name: Terraform Apply
on: push

jobs:
  terraform_init:
    runs-on: self-hosted
    steps:
      - name: Hello World
        run: echo "hello world"

  terraform_apply:
    runs-on: self-hosted
    needs: terraform_init  # ✅ Ensure this runs after `terraform_init`
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Terraform apply
        run: |
        
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          terraform init -backend-config=env-dev/state.tfvars
          terraform apply -var-file=env-dev/main.tfvars -var vault_token=${vault_token} -auto-approve
        env:
          vault_token: ${{ secrets.vault_token }}
